# Generated by Django 5.1.4 on 2024-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_alter_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='من از توییتر فارسی استفاده میکنم!', null=True),
        ),
    ]
