# Generated by Django 5.1.4 on 2024-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0010_hashtag_alter_post_content_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(default=None, related_name='posts', to='Twitter.hashtag'),
        ),
    ]
