# Generated by Django 5.1.4 on 2025-01-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0013_viewpost_delete_view_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequestw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_following', to='Twitter.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_followers', to='Twitter.userprofile')),
            ],
        ),
    ]
